const test=require('node:test');
const assert=require('node:assert/strict');
const C=require('../js/connector.js');
test('extrae id de Google Sheets',()=>assert.equal(C.extractSpreadsheetId('https://docs.google.com/spreadsheets/d/abc_123/edit#gid=0'),'abc_123'));
test('convierte matriz de Sheets a objetos',()=>assert.deepEqual(C.toRows([['SKU','Marca'],['A1','Acme'],['A2','Beta']]),[{SKU:'A1',Marca:'Acme',__row:2},{SKU:'A2',Marca:'Beta',__row:3}]));
test('normaliza payload REST común',()=>assert.deepEqual(C.normalizeRestPayload({items:[{id:1},{id:2}]}),[{id:1},{id:2}]));
test('mapea campos sin inventarlos',()=>assert.deepEqual(C.mapRow({sku:'A1',name:'X'},{SKU:'sku',title:'name',brand:'missing'}),{SKU:'A1',title:'X'}));
test('prepara records con id estable',()=>{const r=C.prepareRecords({sourceId:'rest-api',fetchedAt:'2026-01-01T00:00:00Z',rows:[{sku:'A1',name:'X'}]}, {fieldMap:{SKU:'sku',title:'name'}});assert.equal(r[0].sourceRecordId,'A1');assert.deepEqual(r[0].data,{SKU:'A1',title:'X'});});
test('configuración segura no expone secretos',()=>{const s=C.safeConfig({url:'x',token:'secret',apiKey:'key'});assert.equal(s.token,undefined);assert.equal(s.apiKey,undefined);});
test('GET REST procesa arrays y metadatos',async()=>{const fake=async()=>new Response(JSON.stringify([{id:'1'}]),{status:200,headers:{etag:'e1'}});const r=await C.readRest({url:'https://example.test/api',method:'GET'},fake);assert.equal(r.rows.length,1);assert.equal(r.etag,'e1');});
test('Google Sheets usa rango e id',async()=>{let called='';const fake=async(url,opts)=>{called=url;return new Response(JSON.stringify({range:'Hoja1!A1:B2',values:[['SKU','Marca'],['A1','Acme']]}),{status:200,headers:{etag:'g1'}})};const r=await C.readGoogleSheets({spreadsheetId:'abc',range:'Hoja1!A1:B2',token:'tok'},fake);assert.equal(r.rows[0].SKU,'A1');assert.match(called,/spreadsheets\/abc\/values/);});
